spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  datasource:
    url: jdbc:postgresql://localhost/testRec
    username: postgres
    password: qwerty123z
  jpa:
    generate-ddl: true