spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  datasource:
    url: jdbc:postgresql://localhost/testRec
    username: postgres
    password: qwerty123z
  jpa:
    generate-ddl: true
jwt:
  token:
    secret: secret
    expired: 1800000
server:
  port: 8088